spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ezra?schema=spring
    username: ezra
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect